#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : elementpath
Version  : 2.2.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/a9/4a/0e07cd8098bf41fc3909432893c0f38132346f3764369342db62f7ee1cb6/elementpath-2.2.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/a9/4a/0e07cd8098bf41fc3909432893c0f38132346f3764369342db62f7ee1cb6/elementpath-2.2.3.tar.gz
Summary  : XPath 1.0/2.0 parsers and selectors for ElementTree and lxml
Group    : Development/Tools
License  : MIT
Requires: elementpath-license = %{version}-%{release}
Requires: elementpath-python = %{version}-%{release}
Requires: elementpath-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
elementpath
        ***********

%package license
Summary: license components for the elementpath package.
Group: Default

%description license
license components for the elementpath package.


%package python
Summary: python components for the elementpath package.
Group: Default
Requires: elementpath-python3 = %{version}-%{release}

%description python
python components for the elementpath package.


%package python3
Summary: python3 components for the elementpath package.
Group: Default
Requires: python3-core
Provides: pypi(elementpath)

%description python3
python3 components for the elementpath package.


%prep
%setup -q -n elementpath-2.2.3
cd %{_builddir}/elementpath-2.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1630363926
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/elementpath
cp %{_builddir}/elementpath-2.2.3/LICENSE %{buildroot}/usr/share/package-licenses/elementpath/9f7ea40a3b281ff78d11325e80eb8bcc5b49aa90
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/elementpath/9f7ea40a3b281ff78d11325e80eb8bcc5b49aa90

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
